CREATE TABLE ARTISTA(
    IDARTISTA INT PRIMARY KEY AUTO_INCREMENT,  
	NOME VARCHAR(30) NOT NULL, 
	SEXO ENUM('M','F') NOT NULL
	);
	
	
	CREATE TABLE MUSICA(
	IDMUSICA INT PRIMARY KEY AUTO_INCREMENT,  
	NOME VARCHAR(30) NOT NULL,
	DURACAO VARCHAR(10) NOT NULL,
	ID_ARTISTA INT,
	FOREIGN KEY(ID_ARTISTA)
	REFERENCES ARTISTA(IDARTISTA)
	); 
	
	CREATE TABLE DISCO(
	IDDISCO INT PRIMARY KEY AUTO_INCREMENT,
	GRAVADORA VARCHAR(30) NOT NULL,
	ALBUM VARCHAR(30) NOT NULL,
	ANO INT(4) NOT NULL, 
	COMPOSITOR VARCHAR(30) NOT NULL,
	ID_ARTISTA INT,
	FOREIGN KEY(ID_ARTISTA)
	REFERENCES ARTISTA(IDARTISTA)
	);

	CREATE TABLE OUVINTES(
	IDOUVINTES INT PRIMARY KEY AUTO_INCREMENT,  
	SEGUIDORES VARCHAR(10) NOT NULL,
	EXECUCOES VARCHAR(10) NOT NULL, 
	ID_ARTISTA INT,
	FOREIGN KEY(ID_ARTISTA)
	REFERENCES ARTISTA(IDARTISTA)
	);
	
    
INSERT INTO ARTISTA VALUES(NULL,'DJAVAN','M');
INSERT INTO ARTISTA VALUES(NULL,'NANDO REIS','M');
INSERT INTO ARTISTA VALUES(NULL, 'ROBERTA CAMPOS','F');
INSERT INTO ARTISTA VALUES(NULL, 'MARISA MONTE','F');
INSERT INTO ARTISTA VALUES(NULL, 'MAURICIO MANIERI','M');
INSERT INTO ARTISTA VALUES(NULL,'GIBERTO GIL','M');
INSERT INTO ARTISTA VALUES(NULL,'VANESSA DA MATA','F');
INSERT INTO ARTISTA VALUES(NULL, 'TIM MAIA','M');
INSERT INTO ARTISTA VALUES(NULL, 'LULU SANTOS','M');
INSERT INTO ARTISTA VALUES(NULL, 'ED MOTTA','M');


INSERT INTO MUSICA VALUES(NULL,'EU TE DEVORO','4:56',1);
INSERT INTO MUSICA VALUES(NULL,'UM AMOR PURO','5:27',1);
INSERT INTO MUSICA VALUES(NULL,'ALL STAR','3:53',2);
INSERT INTO MUSICA VALUES(NULL,'DE JANEIRO A JANEIRO','3:12',3);
INSERT INTO MUSICA VALUES(NULL,'CASINHA BRANCA','3:15',3);
INSERT INTO MUSICA VALUES(NULL,'AINDA BEM','4:07',4);
INSERT INTO MUSICA VALUES(NULL,'BEM QUERER','4:00',5);
INSERT INTO MUSICA VALUES(NULL,'A PAZ','4:53',6);
INSERT INTO MUSICA VALUES(NULL,'AMADO','4:09',7);
INSERT INTO MUSICA VALUES(NULL,'GOSTAVA TANTO DE VOCÊ','4:16',8);
INSERT INTO MUSICA VALUES(NULL,'DO LEME AO PONTAL','3:57',8);
INSERT INTO MUSICA VALUES(NULL,'TUDO COM VOCÊ','2:59',9);
INSERT INTO MUSICA VALUES(NULL,'UM CONTRATO COM DEUS','3:27',10);


INSERT INTO DISCO VALUES(NULL,'EPIC RECORDS','BICHO SOLTO','1998','DJAVAN',1);
INSERT INTO DISCO VALUES(NULL,'EPIC RECORDS','DJAVAN - AO VIVO','1999','DJAVAN',1);
INSERT INTO DISCO VALUES(NULL,'WARNER MUSIC BRASIL','O POTE DE OURO','1995','NANDO REIS',2);
INSERT INTO DISCO VALUES(NULL,'DECKDISC','VARRENDO A LUA','2010','ROBERTA CAMPOS',3);
INSERT INTO DISCO VALUES(NULL,'DECKDISC','TODO CAMINHO É SORTE','2015','GILSON',3);
INSERT INTO DISCO VALUES(NULL,'PHONOMOTOR RECORDS','SABER A VERDADE','2011','ARNALDO ANTUNES',4);
INSERT INTO DISCO VALUES(NULL,'ARIOLA RECORDS','A NOITE INTEIRA','1999','MAURICIO MANIERI',5);
INSERT INTO DISCO VALUES(NULL,'WM BRAZIL','UNPLUGGED','1994','JOAO DONATO',6);
INSERT INTO DISCO VALUES(NULL,'SONY BMG','SIM','2007','MARCELO JENECI',7);
INSERT INTO DISCO VALUES(NULL,'UNIVERSAL MUSIC','TIM MAIA 1973','1973','EDSON TRINDADE',8);
INSERT INTO DISCO VALUES(NULL,'VITÓRIA REGIA DISCOS','TIM MAIA IN CONCERT','2007','TIM MAIA',8);
INSERT INTO DISCO VALUES(NULL,'WEA LATINA','O ÚLTIMO ROMÂNTICO','1983','FAUSTO NILO',9);
INSERT INTO DISCO VALUES(NULL,'WM BRAZIL','E - COLLECTION','1990','BOM BOM',10);


INSERT INTO OUVINTES VALUES(NULL,'2.719.730','5.002.807',1);
INSERT INTO OUVINTES VALUES(NULL,'2.912.361','3.529.787',2);
INSERT INTO OUVINTES VALUES(NULL,'366.269','1.896.663',3);
INSERT INTO OUVINTES VALUES(NULL,'2.125.866','2.908.775',4);
INSERT INTO OUVINTES VALUES(NULL,'188.870','226.066',5);
INSERT INTO OUVINTES VALUES(NULL,'1.279.1430','2.823.3006',6);
INSERT INTO OUVINTES VALUES(NULL,'1.214.380','4.034.6436',7);
INSERT INTO OUVINTES VALUES(NULL,'1.852.099','2.990.486',8);
INSERT INTO OUVINTES VALUES(NULL,'1.994.113','3.395.226',9);
INSERT INTO OUVINTES VALUES(NULL,'203.945','269.520',10);





